name: Java CI

on:
  push:
    branches:
      - master      # Trigger CI on push to the master branch
  pull_request:
    branches:
      - master      # Trigger CI on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Set up JDK 17 (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use Java 17 LTS
      
      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Cache Maven repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      # Step 4: Run Maven build and tests
      - name: Build and Test with Maven
        run: mvn clean test  # Run the tests
      
      # Step 5: Upload test results to GitHub Actions as an artifact
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/  # Ensure this matches your test results location
      
      # Step 6: Upload ExtentReport (if generated as HTML)
      - name: Upload ExtentReport
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: report/extent-report.html  # Adjust this path to your ExtentReport file location
