name: Java CI

on:
  push:
    branches:
      - main      # Trigger CI on push to the main branch
  pull_request:
    branches:
      - main      # Trigger CI on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu machine
    
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Step 2: Set up JDK (Java Development Kit)
    - name: Set up JDK 15
      uses: actions/setup-java@v3
      with:
        java-version: '15'  # Use Java 15 or any version you need
    
    # Step 3: Cache Maven dependencies to speed up builds
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository  # Cache Maven repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    # Step 4: Run Maven build and tests
    - name: Build with Maven
      run: mvn clean install -DskipTests=false  # Run tests as part of the build

    # Step 5: Upload test results to GitHub Actions as an artifact
    - name: Upload test results as artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/test-*.xml  # Path to your test result XML files generated by Maven
