name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install dependencies
        run: mvn install

      - name: Run Tests
        run: mvn test

      - name: Upload XML Report
        uses: actions/upload-artifact@v2
        with:
          name: testupdate-xml
          path: src/test/resources/testupdate.xml
